apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-grid-auth-service
  labels:
    app: msg-grid-auth-service

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: msg-grid-auth
  template:
    metadata:
      labels:
        app: msg-grid-auth
    spec:
      containers:
        - name: msg-grid-auth
          image: vaishakhgk/msg-grid-auth
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: msg-grid-auth-configmap
